= Plan your things to be done with tasks
:nofooter:
:toc:

= What is a task?

A *task* represents a thing that must be done (Todo).
Tasks can be hierachical.
A task can be associated to one jira issue

= Create a task

There are multiple ways to create a new task:

* On the commandline call ``s t create [TASKNAME]`` to create a task and name it [TASK].
* In the fxclient call *Show tasks* in the tray menu, type your taskname into the textfield of the opened page and press *CR* to finish.

= Show tasks

There are multiple ways to show your tasks:
* On the commandline call ``s t list`` to show a list of all available tasks.
* In the fxclient you see all tasks when you call *Show tasks* in the tray menu.

= Remove an existing task

There are multiple ways to remove an existing task:

* On the commandline call ``s t remove [NAME | ID]]`` to remove a certain task.
* In the fxclient call *Show tasks* in the tray menu, select the task to be removed and press *-* to remove the selected task.

= Set parent task of a task

As said tasks can be hierarchical. If you want to change the parent task of any task call "Show tasks"
in the fx-client, double click on a task in the list and in the details view change the parent task.

